name: hash_attendance
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  get: ^4.6.6
  sqflite: ^2.3.3
  geolocator: ^11.0.0
  google_maps_flutter: ^2.6.0
  intl: ^0.19.0
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
